services:
  backend:
    build: ./search_engine
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network


  frontend:
    build: ./streamlit_ui
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
